name: lint

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: docker compose run lint
